/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform --types 
Files: scene.gltf [7.86KB] > /Users/weishuokun/mycode/electron/electron-vite-react/src/assets/model/shiba/scene-transformed.glb [44.22KB] (-463%)
Author: zixisun02 (https://sketchfab.com/zixisun51)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shiba-faef9fe5ace445e7b2989d1c1ece361c
Title: Shiba
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Group18985_default_0: THREE.Mesh
  }
  materials: {
    ['default']: THREE.MeshBasicMaterial
  }
  animations: any
}

export function RobotModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/robot-model.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Group18985_default_0.geometry} material={materials['default']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/robot-model.glb')
